# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         PDF-OCR
version:      1.02
version_from: lib/PDF/OCR.pm
installdirs:  site
requires:
    Carp:                          0
    Dyer::CLI:                     0
    File::Copy:                    0
    File::Path:                    0
    File::Slurp:                   0
    File::Which:                   0
    Image::Magick:                 0
    PDF::API2:                     0
    Smart::Comments:               0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
